runtime: nodejs10
service: default

env_variables:
  REACT_APP_BACKEND_URL: 'https://api.kavok.fr'

handlers:
  - url: /static
    static_dir: build/static
    secure: always
    redirect_http_response_code: 301

  - url: /(.*\.(json|ico|js))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js)$
    secure: always
    redirect_http_response_code: 301

  - url: .*
    static_files: build/index.html
    upload: build/index.html
    secure: always
    redirect_http_response_code: 301
