version: '3.4'

services:
  postgresql:
    image: 'postgres:11.3'
    environment:
      - POSTGRES_USER=the
      - POSTGRES_PASSWORD=cafe
      - POSTGRES_DB=theodercafe
    ports:
      - '5432:5432'
  backend:
    build: ./backend
    command: npm run start:dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
    ports:
      - "4000:4000"
    depends_on:
      - postgresql
  react:
    build: ./mobile
    command: yarn start
    volumes:
      - ./mobile:/app
    ports:
      - "19000:19000"
      - "19001:19001"
  nginx:
    image: nginx
    volumes:
      - './devops/dev/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '80:80'
    depends_on:
      - backend
      - react
    links:
      - backend
      - react
