version: '3.4'

services:
  postgresql:
    image: 'postgres:11.3'
    environment:
      - POSTGRES_USER=the
      - POSTGRES_PASSWORD=cafe
      - POSTGRES_DB=theodercafe
    ports:
      - '5432:5432'
