---
- hosts: all
  gather_facts: False

  tasks:
    - name: Ansible check directory exists example.
      stat:
        path: kavok
      register: project_folder

    - name: Clone project
      raw: "git clone https://github.com/victorbrun/kavok.git"
      when: not project_folder.stat.exists

    - name: Pull project
      raw: "cd kavok && git fetch && git reset --hard origin/master"

    - name: Restart backend
      raw: "cd kavok/backend && npm install && npm run build && npm run migration:run && pm2 restart npm"

    - name: Build frontend
      raw: "cd kavok/frontend && npm install && npm run build"

    - name: Copy final build in the served folder
      raw: "cp -r kavok/frontend/build/. kavok/frontend/build-prod"
